
//	Please keep sorted alphabetically

	// lowercase
	TOK(a,0),
	TOK(b,		F_BOLD),
        TOK(big,	F_SIZE1),
	TOK(body,	F_BLOCK),
	TOK(br,		0),
	TOK(button,0),
	TOK(content_type,0),
	TOK(date,0),
	TOK(description,0),
	TOK(div,	F_BLOCK),
	TOK(em,		F_BOLD),
	TOK(form,0),
	TOK(from,0),
        TOK(h1,		F_BLOCK|F_SIZE2|F_BOLD),
        TOK(h2,		F_BLOCK|F_SIZE2),
        TOK(h3,		F_BLOCK|F_SIZE1|F_BOLD),
        TOK(h4,		F_BLOCK|F_SIZE1),
        TOK(h5,		F_BLOCK|F_SIZE0|F_BOLD),
        TOK(h6,		F_BLOCK|F_SIZE0),
	TOK(head,0),
        TOK(hr,		F_BLOCK),
	TOK(href,	0),
	TOK(html,	0),
	TOK(i,		F_ITALIC),
	TOK(img,0),
	TOK(input,0),
	TOK(item,0),
	TOK(li,		F_BLOCK),
	TOK(link,0),
	TOK(meta,0),
	TOK(ol,		F_BLOCK),
	TOK(p,		F_BLOCK),
	TOK(received,0),
	TOK(script,0),
	TOK(span,0),
	TOK(strong,	F_BOLD),
	TOK(style,0),
	TOK(subject,0),
	TOK(title,0),
	TOK(to,0),
	TOK(uid,0),
	TOK(ul,		F_BLOCK),
